
import 'package:flutter/material.dart';
import 'package:money_analyzer/screens/CSmenu.dart';
import 'screens/Scanner.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF86BBB2),
      ),
      home: Scaffold(
        body: ListView(children: [
          Firstpage(),
        ]),
      ),
    );
  }
}

class Firstpage extends StatefulWidget {
  const Firstpage({super.key});

  @override
  _FirstPageState createState() => _FirstPageState();
}

class _FirstPageState extends State<Firstpage> {
  bool _isVisible = false; // Visibility flag

  void _toggleVisibility() {
    setState(() {
      _isVisible = !_isVisible; // Toggle visibility
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 360,
          height: 800,
          child: Stack(
            children: [
              Positioned(
                left: 11,
                top: 274,
                child: SizedBox(
                  width: 197,
                  height: 180,
                  child: Text(
                    'HELLO, LET’S ANALYZE!',
                    style: TextStyle(
                      color: const Color(0xFF422655),
                      fontSize: 40,
                      fontFamily: 'Righteous',
                      fontWeight: FontWeight.w400,
                      shadows: [
                        Shadow(
                          offset: const Offset(0, 4),
                          blurRadius: 4,
                          color: const Color(0xFF000000).withAlpha(25),
                        )
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 228,
                top: 206,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  child: Container(
                    width: 316,
                    decoration: const ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Color(0xFF422655),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 249,
                top: 330,
                child: Container(
                  width: 70,
                  height: 70,
                  padding: const EdgeInsets.all(12),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF422655),
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(width: 1, color: Color(0xFF86BBB2)),
                      borderRadius: BorderRadius.circular(32),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 20,
                        height: 20,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(),
                        child: const FlutterLogo(),
                      ),
                      GestureDetector(
                        onTap: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(builder: (context) => const AndroidCompact1())
                          );
                        }
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 313,
                top: 741,
                child: SizedBox(
                  width: 30,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF422655),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1.97,
                        top: 2.43,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.02),
                        ),
                      ),
                      ElevatedButton(
                        onPressed: _toggleVisibility,
                        child: null,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                bottom: 30,
                right: 50,
                child: 
                  _isVisible
                          ? Align(
                              alignment: Alignment.bottomCenter,
                              child: MoreMenu(toggleVisibility: _toggleVisibility),
                            )
                          : const SizedBox(),
              )
            ],
          ),
        ),
      ],
    );
  }
}
